name       : libvirt-python
version    : 4.8.0
release    : 16
source     :
    - https://libvirt.org/sources/python/libvirt-python-4.8.0.tar.gz : 05cc7d0fb0ef415cf9411bee43dde3fa3f08e43a70ca386b0727e2e97c7311ee
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
