name       : libvirt-python
version    : 4.3.0
release    : 12
source     :
    - https://libvirt.org/sources/python/libvirt-python-4.3.0.tar.gz : efe384479a0bf74b1b83bba208887b263cc0061fd4f87759cf3067a403618ea9
license    : LGPL-2.0
summary    : The libvirt virtualization API python binding
component  : programming.python
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
