name       : libvirt-python
version    : 6.1.0
release    : 19
source     :
    - https://libvirt.org/sources/python/libvirt-python-6.1.0.tar.gz : be644f4809c0e1d368e3ac065df3c66a26dcfe61ecb607ee9706e1799f22c35a
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
