name       : libvirt-python
version    : 9.5.0
release    : 40
source     :
    - https://libvirt.org/sources/python/libvirt-python-9.5.0.tar.gz : 8b6ace0810528ec020e121bf1a142c12f786b12c130c7899e9397f0f3a82c392
license    : LGPL-2.1-or-later
homepage   : https://libvirt.org/
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
