name       : libvirt-python
version    : 9.4.0
release    : 39
source     :
    - https://libvirt.org/sources/python/libvirt-python-9.4.0.tar.gz : 2d0adcb54ca1dd1ddc72b45a39894941ff3659f18d61382229ed9029f6274a7f
license    : LGPL-2.1-or-later
homepage   : https://libvirt.org/
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
