name       : libvirt-python
version    : 8.10.0
release    : 35
source     :
    - https://libvirt.org/sources/python/libvirt-python-8.10.0.tar.gz : fc30f136abe0b8228029a90814c8f44ac2947433c12f211363051c57df2d5401
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
