name       : libvirt-python
version    : 8.4.0
release    : 29
source     :
    - https://libvirt.org/sources/python/libvirt-python-8.4.0.tar.gz : 6d252ad4e0f765620bbde450be8f2b844e4f85c568b207ac644f52c6a982f46c
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
