name       : libvirt-python
version    : 1.2.20
release    : 3
source     :
    - https://pypi.python.org/packages/source/l/libvirt-python/libvirt-python-1.2.20.tar.gz : e1ea097546edc7cb0e7fd01e2ca9906ac12cc4f16d07f15f8f0f5154626ba446
license    : LGPL-2.0+
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
