name       : libvirt-python
version    : 3.3.0
release    : 7
source     :
    - https://github.com/libvirt/libvirt-python/archive/v3.3.0.tar.gz : f889a5b875dea6000075cd81488bf3b036fd5c27793f6ff8f502ba449d9b3773
license    : LGPL-2.0+
summary    : The libvirt virtualization API python binding
component  : programming.python
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
build      : |
    %python_setup
install    : |
    %python_install
