name       : libvirt-python
version    : 8.7.0
release    : 32
source     :
    - https://libvirt.org/sources/python/libvirt-python-8.7.0.tar.gz : 60dcb571e44b6f0d7ca812addb513feac863c3c6c02282871cdfdcda5104dbb3
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
