name       : libvirt-python
version    : 3.5.0
release    : 8
source     :
    - https://libvirt.org/sources/python/libvirt-python-3.5.0.tar.gz : 5c5fee90bebf39d318ef55545077431c3da9ae8b6352adfa461fa4492a03ac1a
license    : LGPL-2.0
summary    : The libvirt virtualization API python binding
component  : programming.python
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
