name       : libvirt-python
version    : 3.0.0
release    : 6
source     :
    - https://github.com/libvirt/libvirt-python/archive/v3.0.0.tar.gz : 67c106edace70e5f1a42402baff85d44db2e36129a63cf90b391f29768bbf081
license    : LGPL-2.0+
summary    : The libvirt virtualization API python binding
component  : programming.python
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
build      : |
    %python_setup
install    : |
    %python_install
