name       : libvirt-python
version    : 1.3.3
release    : 5
source     :
    - https://pypi.python.org/packages/source/l/libvirt-python/libvirt-python-1.3.3.tar.gz : aa68ae788d44ae49ee43be69227f1db2e8c55a2b3499236b715dfbf6090c0e4a
license    : LGPL-2.0+
summary    : The libvirt virtualization API python binding
component  : programming.python
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
