name       : libvirt-python
version    : 3.9.0
release    : 9
source     :
    - https://libvirt.org/sources/python/libvirt-python-3.9.0.tar.gz : d721c812e002eb784a4b66fbe698dc70e8f42c9b7cc3a96f5b01e83ee7951850
license    : LGPL-2.0
summary    : The libvirt virtualization API python binding
component  : programming.python
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
