name       : libvirt-python
version    : 8.9.0
release    : 34
source     :
    - https://libvirt.org/sources/python/libvirt-python-8.9.0.tar.gz : 2e1cfc3b9bd288b3cac400a6b03593633814236dbd1ecf5a900057bb90181c65
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
