name       : libvirt-python
version    : 4.5.0
release    : 14
source     :
    - https://libvirt.org/sources/python/libvirt-python-4.5.0.tar.gz : ef35ed6bc24d76563b1ba9b068ef5a048016726dba62a9d057fe6dfbea6b0f60
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
