name       : libvirt-python
version    : 9.3.0
release    : 38
source     :
    - https://libvirt.org/sources/python/libvirt-python-9.3.0.tar.gz : 9c761d88b4ddcf65b324043944da4f18f82471c74d9371d2372d3b4e0f19861b
license    : LGPL-2.1-or-later
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
